/* TODO: Test ids update properly. */
alter table IDENTIFICATION_ANALYSIS add column DATABASE_ID VARCHAR(255);
alter table IDENTIFICATION_ANALYSIS add index FK7112898DF7AF0B79 (DATABASE_ID), add constraint FK7112898DF7AF0B79 foreign key (DATABASE_ID) references DATABASE_TABLE (OBJECT_ID);

update IDENTIFICATION_ANALYSIS A set A.DATABASE_ID = (select P.DATABASE_ID from IDENTFICATION_PARAMETERS P where P.PARAMETERS_ID = A.PARAMETERS_ID);

ALTER TABLE IDENTFICATION_PARAMETERS drop FOREIGN KEY FKA7FA4DA4F7AF0B79;
drop index FKA7FA4DA4F7AF0B79 ON IDENTFICATION_PARAMETERS;
alter table IDENTFICATION_PARAMETERS drop column DATABASE_ID;
/* DROP UNIQUENESS OF PARAMETERS_ID */


ALTER TABLE IDENTIFICATION_ANALYSIS  DROP INDEX FK7112898D978FD027;

ALTER TABLE IDENTIFICATION_ANALYSIS DROP FOREIGN KEY FK7112898D978FD027;
ALTER TABLE IDENTIFICATION_ANALYSIS DROP KEY `PARAMETERS_ID`;
alter table IDENTIFICATION_ANALYSIS add index FK7112898D978FD027 (PARAMETERS_ID), add constraint FK7112898D978FD027 foreign key (PARAMETERS_ID) references IDENTFICATION_PARAMETERS (PARAMETERS_ID);



alter table JOB drop foreign key FK11F9D9DEBD0F9;
alter table TROPIX_OBJECT_JOB drop foreign key FK4E5AED2E47DEDD67;
alter table TROPIX_OBJECT_JOB drop foreign key FK4E5AED2EF218A59B;
drop table JOB;
drop table TROPIX_OBJECT_JOB;