package edu.umn.msi.tropix.storage.cagrid.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
@SuppressWarnings("all") public interface TropixStorageI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  public boolean delete(java.lang.String arg1) throws RemoteException ;

  public boolean exists(java.lang.String arg1) throws RemoteException ;

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference prepareDownload(java.lang.String arg1) throws RemoteException ;

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference prepareUpload(java.lang.String arg1) throws RemoteException ;

  public boolean canDownload(java.lang.String arg1) throws RemoteException ;

  public boolean canUpload(java.lang.String arg1) throws RemoteException ;

  public boolean canDelete(java.lang.String arg1) throws RemoteException ;

}

