Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  # config.vm.boot_mode = :gui
  # config.vm.network "33.33.33.10"
  # config.vm.forward_port "http", 80, 8080

  config.vm.share_folder "project-data", "/tint", ".."

  config.vm.provision :puppet do |puppet|
    puppet.pp_path = "/tmp/vagrant-puppet"
    puppet.module_path = "modules"
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "site.pp"
  end

  config.vm.define :webapp do |webapp|
    webapp.vm.host_name = "webapp"
    webapp.vm.network "33.33.33.10"
  end

  # config.vm.provision :puppet_server do |puppet|
  #   puppet.puppet_server = "positron.msi.umn.edu"
  # end

end
