Vagrant::Config.run do |config|
  #apt_cache = (ENV['APTCACHE'] or "#{ENV['HOME']}/.vmaptcache/")
  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  # config.vm.boot_mode = :gui
  # config.vm.network "33.33.33.11"
  # config.vm.forward_port "http", 80, 8080

  config.vm.share_folder "project-data", "/tint", ".."

  #if defined?(NFS) && NFS
  #  FileUtils.mkdir_p("#{apt_cache}/archives/partial")
  #  config.vm.share_folder "vagrant-apt-cache", "/var/cache/apt", apt_cache, :nfs => true
  #end

  config.vm.provision :puppet do |puppet|
    puppet.pp_path = "/tmp/vagrant-puppet"
    puppet.module_path = "modules"
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "site.pp"
  end

  #config.vm.customize do |vm|
  #  vm.memory_size = 512
  #  vm.name = "My Project VM"
  #end

  config.vm.define :webapp do |webapp|
    webapp.vm.host_name = "webapp"
    webapp.vm.network :hostonly, "33.33.33.11"
  end

  #config.vm.define :sshserver do |sshserver| 
  #  sshserver.vm.host_name = "sshserver"
  #  sshserver.vm.network :hostonly, "33.33.33.11" 
  #  sshserver.vm.forward_port "tint_ssh", 8021, 18021
  #end

end
