<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TransferService" targetNamespace="http://transfer.cagrid.org/TransferService/bindings" xmlns:porttype="http://transfer.cagrid.org/TransferService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://transfer.cagrid.org/TransferService" location="TransferService.wsdl"/>
  <wsdl:binding name="TransferServicePortTypeSOAPBinding" type="porttype:TransferServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getServiceSecurityMetadata">
      <soap:operation soapAction="http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity/GetServiceSecurityMetadataRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
